import { Patient, AnalyticsData, Notification } from '../types';

export const mockPatients: Patient[] = [
  {
    id: 'p001',
    name: 'Eleanor Harrington',
    age: 67,
    gender: 'Female',
    bloodType: 'A+',
    condition: 'Cardiac Arrhythmia',
    status: 'Critical',
    admittedDate: '2024-03-10',
    doctor: 'Dr. Marcus Chen',
    ward: 'Cardiology ICU',
    phone: '+1 (555) 234-5678',
    email: 'e.harrington@email.com',
    address: '142 Maple Grove, Boston, MA 02101',
    insurance: 'BlueCross Premier',
    lastVisit: '2024-03-10',
    nextAppointment: '2024-03-17',
    vitals: { heartRate: 112, bloodPressure: '158/94', temperature: 37.8, oxygenSaturation: 94, weight: 68, height: 165 },
    medications: [
      { name: 'Metoprolol', dosage: '50mg', frequency: 'Twice daily', startDate: '2024-03-10' },
      { name: 'Warfarin', dosage: '5mg', frequency: 'Once daily', startDate: '2024-03-10' },
    ],
    notes: 'Patient admitted with acute onset palpitations. ECG showing intermittent atrial fibrillation.',
  },
  {
    id: 'p002',
    name: 'James Whitmore',
    age: 45,
    gender: 'Male',
    bloodType: 'O-',
    condition: 'Type 2 Diabetes',
    status: 'Stable',
    admittedDate: '2024-03-08',
    doctor: 'Dr. Priya Sharma',
    ward: 'Endocrinology',
    phone: '+1 (555) 345-6789',
    email: 'j.whitmore@email.com',
    address: '78 Oak Street, Chicago, IL 60601',
    insurance: 'Aetna Gold',
    lastVisit: '2024-02-15',
    nextAppointment: '2024-03-22',
    vitals: { heartRate: 78, bloodPressure: '132/84', temperature: 36.9, oxygenSaturation: 98, weight: 92, height: 180 },
    medications: [
      { name: 'Metformin', dosage: '1000mg', frequency: 'Twice daily', startDate: '2023-06-01' },
      { name: 'Lisinopril', dosage: '10mg', frequency: 'Once daily', startDate: '2024-01-15' },
    ],
    notes: 'Blood glucose levels stabilizing. Patient showing good compliance with medication regimen.',
  },
  {
    id: 'p003',
    name: 'Sophia Nakamura',
    age: 29,
    gender: 'Female',
    bloodType: 'B+',
    condition: 'Pneumonia',
    status: 'Recovering',
    admittedDate: '2024-03-05',
    doctor: 'Dr. Ahmed Al-Hassan',
    ward: 'Pulmonology',
    phone: '+1 (555) 456-7890',
    email: 's.nakamura@email.com',
    address: '23 Pine Avenue, Seattle, WA 98101',
    insurance: 'United Health Care',
    lastVisit: '2024-03-05',
    nextAppointment: '2024-03-19',
    vitals: { heartRate: 88, bloodPressure: '118/76', temperature: 38.1, oxygenSaturation: 96, weight: 58, height: 162 },
    medications: [
      { name: 'Amoxicillin', dosage: '500mg', frequency: 'Three times daily', startDate: '2024-03-05' },
      { name: 'Azithromycin', dosage: '250mg', frequency: 'Once daily', startDate: '2024-03-05' },
    ],
    notes: 'Chest X-ray showing improvement. Patient responding well to antibiotic therapy.',
  },
  {
    id: 'p004',
    name: 'Robert Castellano',
    age: 72,
    gender: 'Male',
    bloodType: 'AB+',
    condition: 'Hip Replacement Recovery',
    status: 'Recovering',
    admittedDate: '2024-03-01',
    doctor: 'Dr. Lisa Park',
    ward: 'Orthopedics',
    phone: '+1 (555) 567-8901',
    email: 'r.castellano@email.com',
    address: '56 Elm Court, Miami, FL 33101',
    insurance: 'Medicare Advantage',
    lastVisit: '2024-03-01',
    nextAppointment: '2024-03-20',
    vitals: { heartRate: 72, bloodPressure: '128/80', temperature: 36.7, oxygenSaturation: 99, weight: 84, height: 175 },
    medications: [
      { name: 'Oxycodone', dosage: '5mg', frequency: 'Every 6 hours PRN', startDate: '2024-03-01' },
      { name: 'Aspirin', dosage: '81mg', frequency: 'Once daily', startDate: '2024-03-01' },
    ],
    notes: 'Post-op day 12. Physical therapy progressing well. Pain well-controlled.',
  },
  {
    id: 'p005',
    name: 'Amara Osei',
    age: 34,
    gender: 'Female',
    bloodType: 'O+',
    condition: 'Hypertension',
    status: 'Stable',
    admittedDate: '2024-03-09',
    doctor: 'Dr. Marcus Chen',
    ward: 'Cardiology',
    phone: '+1 (555) 678-9012',
    email: 'a.osei@email.com',
    address: '91 Birch Lane, Atlanta, GA 30301',
    insurance: 'Cigna PPO',
    lastVisit: '2024-02-20',
    nextAppointment: '2024-03-23',
    vitals: { heartRate: 82, bloodPressure: '145/92', temperature: 36.8, oxygenSaturation: 97, weight: 71, height: 168 },
    medications: [
      { name: 'Amlodipine', dosage: '10mg', frequency: 'Once daily', startDate: '2024-02-01' },
    ],
    notes: 'Blood pressure trending down with medication adjustment. Lifestyle counseling provided.',
  },
  {
    id: 'p006',
    name: 'David Reinholt',
    age: 58,
    gender: 'Male',
    bloodType: 'A-',
    condition: 'Kidney Disease (Stage 3)',
    status: 'Stable',
    admittedDate: '2024-03-07',
    doctor: 'Dr. Priya Sharma',
    ward: 'Nephrology',
    phone: '+1 (555) 789-0123',
    email: 'd.reinholt@email.com',
    address: '34 Cedar Way, Denver, CO 80201',
    insurance: 'Humana Gold',
    lastVisit: '2024-02-28',
    nextAppointment: '2024-03-21',
    vitals: { heartRate: 76, bloodPressure: '140/88', temperature: 36.6, oxygenSaturation: 98, weight: 89, height: 182 },
    medications: [
      { name: 'Losartan', dosage: '50mg', frequency: 'Once daily', startDate: '2023-09-15' },
      { name: 'Furosemide', dosage: '20mg', frequency: 'Once daily', startDate: '2024-01-10' },
    ],
    notes: 'eGFR stable at 42. Patient on low-protein diet. Monitoring creatinine levels closely.',
  },
  {
    id: 'p007',
    name: 'Mei Lin Zhou',
    age: 41,
    gender: 'Female',
    bloodType: 'B-',
    condition: 'Anxiety & Depression',
    status: 'Discharged',
    admittedDate: '2024-02-20',
    doctor: 'Dr. Sarah Okonkwo',
    ward: 'Psychiatry',
    phone: '+1 (555) 890-1234',
    email: 'm.zhou@email.com',
    address: '67 Willow Street, Portland, OR 97201',
    insurance: 'Kaiser Permanente',
    lastVisit: '2024-03-08',
    nextAppointment: '2024-03-25',
    vitals: { heartRate: 74, bloodPressure: '116/74', temperature: 36.5, oxygenSaturation: 99, weight: 62, height: 160 },
    medications: [
      { name: 'Sertraline', dosage: '100mg', frequency: 'Once daily', startDate: '2024-02-21' },
      { name: 'Clonazepam', dosage: '0.5mg', frequency: 'As needed', startDate: '2024-02-21' },
    ],
    notes: 'Discharged in stable condition. Follow-up scheduled with outpatient psychiatry.',
  },
  {
    id: 'p008',
    name: 'Marcus Thompson',
    age: 52,
    gender: 'Male',
    bloodType: 'AB-',
    condition: 'Stroke Recovery',
    status: 'Recovering',
    admittedDate: '2024-02-28',
    doctor: 'Dr. Elena Vasquez',
    ward: 'Neurology',
    phone: '+1 (555) 901-2345',
    email: 'm.thompson@email.com',
    address: '12 Spruce Road, Dallas, TX 75201',
    insurance: 'Aetna PPO',
    lastVisit: '2024-02-28',
    nextAppointment: '2024-03-18',
    vitals: { heartRate: 80, bloodPressure: '138/86', temperature: 37.0, oxygenSaturation: 97, weight: 87, height: 178 },
    medications: [
      { name: 'Clopidogrel', dosage: '75mg', frequency: 'Once daily', startDate: '2024-02-28' },
      { name: 'Atorvastatin', dosage: '40mg', frequency: 'Once daily', startDate: '2024-02-28' },
      { name: 'Lisinopril', dosage: '5mg', frequency: 'Once daily', startDate: '2024-02-28' },
    ],
    notes: 'Speech therapy showing good progress. Physical therapy ongoing. CT scan scheduled.',
  },
];

export const mockAnalytics: AnalyticsData = {
  patientAdmissions: [
    { month: 'Sep', count: 142, discharged: 138 },
    { month: 'Oct', count: 158, discharged: 149 },
    { month: 'Nov', count: 134, discharged: 130 },
    { month: 'Dec', count: 167, discharged: 161 },
    { month: 'Jan', count: 189, discharged: 174 },
    { month: 'Feb', count: 201, discharged: 188 },
    { month: 'Mar', count: 178, discharged: 142 },
  ],
  departmentLoad: [
    { name: 'Cardiology', patients: 42, capacity: 50 },
    { name: 'Neurology', patients: 28, capacity: 35 },
    { name: 'Orthopedics', patients: 38, capacity: 40 },
    { name: 'Pulmonology', patients: 25, capacity: 30 },
    { name: 'Nephrology', patients: 19, capacity: 25 },
    { name: 'Psychiatry', patients: 22, capacity: 30 },
  ],
  vitalTrends: [
    { time: '00:00', heartRate: 68, bp: 118 },
    { time: '04:00', heartRate: 62, bp: 112 },
    { time: '08:00', heartRate: 74, bp: 124 },
    { time: '12:00', heartRate: 82, bp: 132 },
    { time: '16:00', heartRate: 78, bp: 128 },
    { time: '20:00', heartRate: 71, bp: 120 },
    { time: '24:00', heartRate: 66, bp: 116 },
  ],
  conditionBreakdown: [
    { name: 'Cardiac', value: 28, color: '#ef4444' },
    { name: 'Neurological', value: 18, color: '#8b5cf6' },
    { name: 'Orthopedic', value: 22, color: '#3b82f6' },
    { name: 'Respiratory', value: 16, color: '#06b6d4' },
    { name: 'Metabolic', value: 24, color: '#f59e0b' },
    { name: 'Other', value: 12, color: '#6b7280' },
  ],
};

export const mockNotifications: Notification[] = [
  {
    id: 'n001',
    title: 'Critical Alert',
    message: 'Eleanor Harrington — O₂ saturation dropped to 91%. Immediate attention required.',
    type: 'alert',
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    read: false,
    patientId: 'p001',
  },
  {
    id: 'n002',
    title: 'Lab Results Ready',
    message: 'Blood panel results for James Whitmore are available for review.',
    type: 'info',
    timestamp: new Date(Date.now() - 23 * 60000).toISOString(),
    read: false,
    patientId: 'p002',
  },
  {
    id: 'n003',
    title: 'Medication Due',
    message: 'Sophia Nakamura — Amoxicillin dose due in 15 minutes.',
    type: 'warning',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    read: false,
    patientId: 'p003',
  },
  {
    id: 'n004',
    title: 'Patient Discharged',
    message: 'Mei Lin Zhou has been successfully discharged. Discharge summary filed.',
    type: 'success',
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    read: true,
    patientId: 'p007',
  },
  {
    id: 'n005',
    title: 'Appointment Reminder',
    message: 'Robert Castellano has a physical therapy session in 30 minutes.',
    type: 'info',
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    read: true,
    patientId: 'p004',
  },
];
